#!/bin/sh

mkdir -p mlfit_m90_expectSignal0
combine -M MaxLikelihoodFit -t -1 --expectSignal 0 -m 90 --out mlfit_m90_expectSignal0 --plots --saveShapes --saveWithUncertainties --saveNormalizations --robustFit=1 --initFromBonly --setPhysicsModelParameterRange BR=0.00,0.10 workspaceM90.root
python /afs/cern.ch/work/a/amagnani/private/COMBINE/CMSSW_7_4_7/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py --all --poi=BR -g mlfit_m90_expectSignal0/mlfit_m90_pull.root mlfit_m90_expectSignal0/mlfit.root > mlfit_m90_expectSignal0/diffNuisances.txt
