#!/bin/sh

mkdir -p mlfit_m90
combine -M MaxLikelihoodFit  -m 90 --out mlfit_m90 --plots --saveShapes --saveWithUncertainties --saveNormalizations --robustFit=1 --initFromBonly --setPhysicsModelParameterRange BR=0.00,0.10 workspaceM90.root
python /afs/cern.ch/work/a/amagnani/private/COMBINE/CMSSW_7_4_7/src/HiggsAnalysis/CombinedLimit/test/diffNuisances.py --all --poi=BR -g mlfit_m90/mlfit_m90_pull.root mlfit_m90/mlfit.root > mlfit_m90/diffNuisances.txt
