#!/bin/sh

../../scripts/text2workspace.py ./mh140.txt -P HiggsAnalysis.CombinedLimit.ChargedHiggs:brChargedHiggs -o workspaceM140.root
combine  -M Asymptotic --picky -v 2  --rMin 0 --rMax 1 -m 140 -n blinded_m140 --rAbsAcc 0.00001 -d workspaceM140.root
