#!/bin/sh

../../scripts/text2workspace.py ./mh160.txt -P HiggsAnalysis.CombinedLimit.ChargedHiggs:brChargedHiggs -o workspaceM160.root
combine  -M Asymptotic --picky -v 2  --rMin 0 --rMax 1 -m 160 -n blinded_m160 --rAbsAcc 0.00001 -d workspaceM160.root
