#!/bin/sh

../../scripts/text2workspace.py ./mh120.txt -P HiggsAnalysis.CombinedLimit.ChargedHiggs:brChargedHiggs -o workspaceM120.root
combine  -M Asymptotic --picky -v 2  --rMin 0 --rMax 1 -m 120 -n blinded_m120 --rAbsAcc 0.00001 -d workspaceM120.root
