#!/bin/sh

../../scripts/text2workspace.py ./mh100.txt -P HiggsAnalysis.CombinedLimit.ChargedHiggs:brChargedHiggs -o workspaceM100.root
combine  -M Asymptotic --picky -v 2  --rMin 0 --rMax 1 -m 100 -n blinded_m100 --rAbsAcc 0.00001 -d workspaceM100.root
