perl -i -ne'/failed/ or print' fileList_QCD.txt
perl -i -ne'/failed/ or print' fileList_WW.txt
perl -i -ne'/failed/ or print' fileList_WZ.txt
perl -i -ne'/failed/ or print' fileList_ZZ.txt
perl -i -ne'/failed/ or print' fileList_DY.txt
perl -i -ne'/failed/ or print' fileList_t.txt
perl -i -ne'/failed/ or print' fileList_tbar.txt
perl -i -ne'/failed/ or print' fileList_s.txt
perl -i -ne'/failed/ or print' fileList_sbar.txt
perl -i -ne'/failed/ or print' fileList_tW.txt
perl -i -ne'/failed/ or print' fileList_tWbar.txt
perl -i -ne'/failed/ or print' fileList_WJets.txt
perl -i -ne'/failed/ or print' fileList_Wbb.txt
perl -i -ne'/failed/ or print' fileList_Zbb.txt
perl -i -ne'/failed/ or print' fileList_TTpow.txt
perl -i -ne'/failed/ or print' fileList_TTJetsSplit.txt
perl -i -ne'/failed/ or print' fileList_TTnlo.txt
perl -i -ne'/failed/ or print' fileList_TTZ.txt
perl -i -ne'/failed/ or print' fileList_TTH.txt
perl -i -ne'/failed/ or print' fileList_TTW.txt
perl -i -ne'/failed/ or print' fileList_data.txt
perl -i -ne'/failed/ or print' fileList_H90.txt
perl -i -ne'/failed/ or print' fileList_H100.txt
perl -i -ne'/failed/ or print' fileList_H110.txt
perl -i -ne'/failed/ or print' fileList_H120.txt
perl -i -ne'/failed/ or print' fileList_H130.txt
perl -i -ne'/failed/ or print' fileList_H140.txt
perl -i -ne'/failed/ or print' fileList_H150.txt
perl -i -ne'/failed/ or print' fileList_H155.txt
perl -i -ne'/failed/ or print' fileList_H160.txt
perl -i -ne'/ciemat/ or print' fileList_data.txt
perl -i -ne'/lib/ or print' fileList_data.txt
perl -i -ne'/zabbix/ or print' fileList_data.txt
perl -i -ne'/boot/ or print' fileList_data.txt
perl -i -ne'/citi/ or print' fileList_data.txt
